services:
  mysql:
    image: "glf9832/mysql-xtrabackup:8.0.28-test"
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
  backuper:
    image: "glf9832/xtrabackup:8.0.28-test"
    ports:
      - "2222:22"
    expose:
      - 22
    restart: always
    volumes:
      - backup_data:/data/backup
  restorer:
    image: "glf9832/xtrabackup:8.0.28-test"
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - backup_data:/data/backup
      - restore_data:/data/restore
volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: ./.testdata/mysqldata
      o: bind
  backup_data:
    driver: local
    driver_opts:
      type: none
      device: ./.testdata/backupdata
      o: bind
  restore_data:
    driver: local
    driver_opts:
      type: none
      device: ./.testdata/restoredata
      o: bind
